### ISSUE TITLE
Detect lane type

### ISSUE THREAD

**Issue by pribadihcr** [TJCVRS/lanenet-lane-detection#2]
Hi @TJCVRS,

I am wondering to detect the type of line, like double yellow line or white, dot line.
Is it possible ?

**Comment by TJCVRS** [comment]
@pribadihcr It's possibile in theory. But you are supposed to have annotated training data for the line you want to detect

**Comment by MaybeShewill-CV** [comment]
@derekwong66 The different colour only represent those lanes are different but not represent they are different of type:)

**Comment by derekwong66** [comment]
@MaybeShewill-CV is it possible to add another multi-label classification branch, which use shared encoder layer to extract feature then use Conv to generate lane classes?

**Comment by MaybeShewill-CV** [comment]
@derekwong66 Thanks a lot

**Comment by gabaebae123** [comment]
> @MaybeShewill-CV I will try. If succeed, I update to u.

Hello, have you achieved it？
